#!/usr/bin/env bash
# Let’s install the ufw firewall and setup a few rules on web-01

# Update package information
sudo apt-get update -y

# Install UFW firewall
sudo apt-get install ufw -y

# Enable UFW
sudo ufw enable

# Set default policies(incoming)
sudo ufw default deny incoming -y

# Set default policies(outgoing)
sudo ufw default allow outgoing -y

# Allow SSH (Port 22)
sudo ufw allow 22/tcp

# Allow HTTPS SSL (Port 443)
sudo ufw allow 443/tcp

# Allow HTTP (Port 80)
sudo ufw allow 80/tcp
